stages:
  preprocess_iu_xray_v1.0:
    cmd: uv run python scripts/data/preprocessing/iu-xray/run.py
      --config scripts/data/preprocessing/iu-xray/config_iu-xray_v1.0.yaml
    deps:
      - scripts/data/preprocessing/iu-xray/run.py
      - scripts/data/preprocessing/iu-xray/config_iu-xray_v1.0.yaml
      - src/shield/data/preprocessing.py
      - dataset/iu-xray/original
      - dataset/iu-xray/iu_xray_r2gen/annotation.json
      - dataset/iu-xray/iu_xray_r2gen/images
    outs:
      - dataset/iu-xray/iu-xray_v1.0
